# Data loader configuration
data:
  dataset: "movielens"
  batch_size: 512
  normalize_data: False
  category: "1m"
  embedding_dimension: "user" # 'user' or 'item' or 'relation' or 'entity'

# Model configuration
model:
  input_dimension: 768
  hidden_dimensions: [512, 256, 128]
  latent_dimension: 256
  codebook_clusters: 512
  num_codebook_layers: 3
  commitment_weight: 0.3

# Training configuration
train:
  learning_rate: 5e-4
  weight_decay: 1e-5
  num_epochs: 1024

# Additional configuration
general:
  use_wandb: True
  wandb_project: "semantic_id_ml_1m"
  wandb_entity: "justin-hangoebl-master-thesis"
  save_model: True
