# Data loader configuration
data:
  dataset: "movielens"
  batch_size: 128
  normalize_data: False
  category: "100k"
  embedding_dimension: "user" # 'user' or 'item' or 'relation' or 'entity'

# Model configuration
model:
  input_dimension: 768
  hidden_dimensions: [768, 256]
  latent_dimension: 256
  num_codebook_layers: 2
  codebook_clusters: 256
  commitment_weight: 0.1

# Training configuration
train:
  learning_rate: 1e-3
  weight_decay: 1e-4
  num_epochs: 1024

# Additional configuration
general:
  use_wandb: True
  wandb_project: "semantic_id_ml_100k"
  wandb_entity: "justin-hangoebl-master-thesis"
  save_model: True
