# Data loader configuration
data:
  dataset: "ml"
  batch_size: 1024
  normalize_data: False
  category: "1m"

# Model configuration
model:
  input_dimension: 3706
  hidden_dimensions: [2048, 1024, 512, 256]
  latent_dimension: 256
  num_codebook_layers: 3
  codebook_clusters: 256
  commitment_weight: 0.15

# Training configuration
train:
  learning_rate: 1e-3
  weight_decay: 1e-4
  num_epochs: 1024

# Additional configuration
general:
  use_wandb: True
  wandb_project: "semantic_id_ml_1m"
  wandb_entity: "justin-hangoebl-master-thesis"
  save_model: True
